name: 'Authz0 scanner'
description: 'Unauthorized access can be identified based on URLs and Roles & Credentials.'
branding:
  icon: 'shield'
  color: 'blue'
inputs:
  template:  # id of input
    description: 'Scan template contents'
    required: true
outputs:
  output: 
    description: 'JSON Result'
runs:
  using: 'docker'
  image: 'github-action/Dockerfile'
  args:
    - ${{ inputs.template }}
